# prometheus/prometheus.yml
global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/alert.rules.yml

scrape_configs:
  - job_name: 'demo-app'
    static_configs:
      - targets: ['app:5000'] # 'app' é o nome do serviço no docker-compose

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']